### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#43]
What's our plan for hosting? 

* [x] Save details about each deployed instance #126
* [x] Configure webhook for Jekyll deployment #127
* [x] Configure web server for publishing live #128

**Comment by migurski** [comment]
All the things are checked, but this doesn’t feel done. May need to close this ticket and open a more targeted one.
